### ISSUE TITLE
Node cloning

### ISSUE THREAD

**Issue by effigies** [TimVanMourik/GiraffeTools#114]
It would be nice to have a button that would take an existing node and make a copy with all of the same fields, possibly prepopulated with the same hard-coded (non-connection) values.

**Comment by TimVanMourik** [comment]
Thanks @effigies for the suggestion! I added a new menu with several new buttons like copy/pasting. It copies all parameters including hard-coded values. 

Introduced in 5f03c7999744e57955f3ae7e5ecc42f62e363a6a
