### ISSUE TITLE
Make button to clear database

### ISSUE THREAD

**Issue by AnnaVantVeer** [TimVanMourik/GiraffeTools#124]
**Is your feature request related to a problem? Please describe.**
When starting a new pipeline, would be nice if you can clear the example pipeline with a button.

**Describe the solution you'd like**
A button to clear the working space database.

**Describe alternatives you've considered**
A popup that explains that the example that opens when you add a new project is an example, and that you can remove it to start clean.

**Additional context**
The website also seems to remember past pipelines, I got the Coastal coding example a couple times after clicking 'get started'.

**Comment by TimVanMourik** [comment]
Works started in branch `pretty-svg-menu`. This new menu moves existing buttons to a new menu and allows the addition of new ones.

**Comment by TimVanMourik** [comment]
Done! Added a prettier menu with an option to start over with a clean slate! 

Fixed in 5f03c7999744e57955f3ae7e5ecc42f62e363a6a
