### ISSUE TITLE
Bug in Porcupine

### ISSUE THREAD

**Issue by agni21** [TimVanMourik/GiraffeTools#44]
**Describe the bug**
Nodes for 2nd element in groups can be duplicated.

**To Reproduce**
1. Go to '/porcupine'
2. Drag in the 2nd element of any group
3. Drag in few more elements from same group
4. Drag in the 2nd element again and try moving the resulting Node

**Screenshots**
![bug](https://user-images.githubusercontent.com/19343686/39850070-1b1aa56e-542d-11e8-8c9f-fa295a7b97fc.png)

**Comment by TimVanMourik** [comment]
Hi @agni21! Yes, I noticed this a while ago, but forgot to make an issue out of it. Basically the problem is: whenever you drag a new node in, all nodes with the same name are moved to that same location. I'll look into it! Depending on if I can readily find the problem + fix, I'll post a bounty :)

**Comment by TimVanMourik** [comment]
I rewrote the issue in #46 to have a slightly clearer description. If I understand the problem correctly, that is. Please let me know if the bug that you mention here is the same. If it isn't, I'll reopen this issue.
