### ISSUE TITLE
"wrapped function failed : TypeError: Cannot read property 'state' of undefined"

### ISSUE THREAD

**Issue by TimVanMourik** [TimVanMourik/GiraffeTools#67]
**Describe the bug**
Upon dragging a node, the console displays an error:
> wrapped function failed : TypeError: Cannot read property 'state' of undefined

**To Reproduce**
1. Drag node in porcupine app
2. check console

**Expected behavior**
Not showing an error. Investigate the source of the problem and fix it, if possible.

**Comment by arun1595** [comment]
@TimVanMourik Let me fix it.

**Comment by TimVanMourik** [comment]
Closing this issue. This had to do with jsPlumb and is not relevant anymore with the new React implementation.
