### ISSUE TITLE
List of simple UI/UX updates

### ISSUE THREAD

**Issue by TimVanMourik** [TimVanMourik/GiraffeTools#75]
* [x] Make sure dragging doesn't trigger click event
* [x] Make sure port click doesn't trigger click event
* [x] Make tooltip move along dragged node
* [x] Delete Links on cascade when Node is deleted
* [x] Make link clickable (and deletable)

[to be added to]

**Comment by Losses** [comment]
Add a search field on the left and right side bar may make selecting tools more convinent? :D

**Comment by TimVanMourik** [comment]
@Losses, yes, good one. You can make a separate issue as 'feature request' about that if you like, as that would in no way be a 'simple' update :)

**Comment by Losses** [comment]
Done! ⁽⁽ ◟(∗ ˊωˋ ∗)◞ ⁾⁾

**Comment by TimVanMourik** [comment]
List of points was fixed a while ago. As the application is growing bigger, update requests are now preferably tracked in separate issues
