### ISSUE TITLE
Code Review: Redux

### ISSUE THREAD

**Issue by KennethAshley** [TimVanMourik/GiraffeTools#82]
## Containers vs Components

> /components versus /containers. In some examples I saw this directory structure. At the moment I used the naive distinction that a component is everything that doesn't contain anything. Is this distinction useful at all, might there be a clearer/more principled way?

So the thought behind Containers and Components is a separation of concerns. Here is a comment from the creator of Redux:

> I call components encapsulated React components that are driven solely by props and don't talk to Redux. Same as “dumb components”. They should stay the same regardless of your router, data fetching library, etc.
> 
> I call containers React components that are aware of Redux, Router, etc. They are more coupled to the app. Same as “smart components”.

[Link to comment](https://github.com/reduxjs/redux/issues/756#issuecomment-141683834)

Containers also usually don’t have any DOM markup and they never have styles. In some applications I have seen containers also referred to as ‘connectors’, which might help with understanding the use of containers. Lets look at your app for an example of how we would use containers in this way:

`/containers/links.js` can be changed to `/containers/linksContainer.js` and can be refactored like so:

```
import { connect } from 'react-redux';
import { linksWithPorts } from '../selectors/selectors';
import Links from '../components/Links';

const mapStateToProps = state => ({ 
  links: linksWithPorts(state),
});

const LinksContainer = connect(mapStateToProps)(Links);

export default LinksContainer;
```

We now would import the LinksContainer in whatever component we want, which currently is `canvas.js`.

In `linksContainer.js` we are importing the currently nonexistent `Links` component so we need to create it and code it in a way that works well with our new container. It would look at bit like this:

`/components/Links.js`

```
import React, { Fragment } from 'react';
import Link from './components/Link';

const Links = ({ links }) => (
  <Fragment>
    { links.map(link => (
        <Link {...link} />
      )
    )}
  </Fragment>
);

export default Links;
```

The `Links` component is dumb as its only responsibility is to present something to the DOM. Which it seems as though the current implementation of `links.js` is already dumb but it doesn’t seem to be coded in a dumb way. 

[Here](https://medium.com/@thejasonfile/dumb-components-and-smart-components-e7b33a698d43) is an article on dumb components

In the newly created `Links` component we are importing the `Link` component which currently is connected so we probably would want to turn that into a container as well like this:

`/containers/LinkContainer.js`

```
import { connect } from 'react-redux';
import { connectLink, deleteLink } from '../actions';
import Link from '../components/Link';

const mapStateToProps = state => ({ 
  linkInConstruction: state.scene.linkInConstruction,
  mouseState: state.scene.mouseState,
});

const mapDispatchToProps = dispatch => ({
  connectLink: (linkId, portFrom, portTo) => dispatch(connecLink(linkId, portFrom, portTo)),
  deleteLink: (linkId) => dispatch(deleteLink(linkId)),
});

const LinkContainer.js = connect(mapStateToProps, mapDispatchToProps)(Links);

export default LinkContainer;
```

Then we would refactor the `Link` component like so:

`components/Link.js`

```
import React from 'react';
import PropTypes from 'prop-types';
import { PathLine } from 'react-svg-pathline';

class Link extends React.Component {
  ... \\ pretty much the same code as what is currently there
}

export default Link;
```

I think you can refactor most of the items in the `/containers` folder to use this approach. 

In using this approach I have found that it just helps me wrap my head around what does what a bit easier. I could reuse the same components with a different container and have the preform a bit different then with another container. This approach also helps with overusing the `connect` statement.

## Redux

For the most part I think the redux side of your app looks good. The way you are using redux is pretty standard and currently you are pretty much just setting things in the state. 

I get why you just have a scene reducer but it might make sense to break out the scene reducer into several different files like so if there will be more complicated actions:

```
/reducers
  scene.js
  node.js
  link.js
  index.js
```

Actually i believe in the future we will want to do things like connecting nodes with a link. These actions most likely will effect the node.js, link.js, and possibly scene.js reducers. If we keep just the scene.js then that reducer will probably get pretty verbose. So i’d recommend breaking that up.

Also to see your store in your console id suggest using the [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en). Its great for debugging. 

## Redux-orm

I see you got help from @haveyaseen. Maybe after you submitted the issue on Gitcoin. Did you gain the understanding you needed on `redux-orm`?

**Comment by TimVanMourik** [comment]
Thanks a lot @KennethAshley, this is incredibly helpful! I'm new to Redux(-ORM), so this really gives me a better understanding of the design philosophy. The things I encountered while implementeing these suggestions:

* I added Redux DevTools, good suggestion :)
* A small detail that you might have left out for clarity's sake: React wants keys for fragment list:
```
import React, { Fragment } from 'react';
import Link from './components/Link';

const Links = ({ links }) => (
  <Fragment>
    { links.map(link => (
        <Link 
          {...link}
          key={link.id} //key added
        />
      )
    )}
  </Fragment>
);

export default Links;
```
* After the refactoring, we'll always be calling containers, not components directly. So in the code above, `<Link>` will be `<LinkContainer>`, right? Or is there a way to more silently mount the props onto the components, such that the components are agnostic about the containers?
* The above `<Links>` component is almost identical to the `<Nodes>` component. Would it be a smart move to make a generic component from it with Class as input?
* The Redux-ORM took a while, but I think it all looks quite neat. The little help from @haveyaseen was just what I needed to better understand the logic behind it, and I'm happy with the current implementation.

**Comment by KennethAshley** [comment]
- Yea you'll have to add a key and i think using `link.id` is the best way to go. 
- So ideally you'd have all you need in `<LinksContainer />` and `<Link />`. So you wouldn't even need a container for `<Link />` but of course that depends on what you are tying to do. For example, you'd have a `<ArticlesContainer />` that imports an `<Articles />` component that list many `<Article />` components. Sometimes thats it. But maybe an `<Article />` has some actions and needs to get some items from the store so you could have an `<ArticleContainer />` that is called in `<Articles />`.
- Yea i think condensing that component is always good, again that depends on what each component will do. 

If you want some help refactoring i'd love to help!

**Comment by TimVanMourik** [comment]
Ok, clear! In this round of refactoring, the larger number of classes became component/container pairs. I think in a next round I'll be 'dumbing down' the components. I'm reasonably certain that with some refactoring I can cut down on the number of containers substantially, and thereby on store subscriptions.

So far, it's a big improvement already. Smart and dumb components are now completely separated. I hope this is going to help me in the future to put issues/bounties on presentational components only and being clearer in the desired outcome.

This was a incredibly helpful already! Further refactoring is somewhat lower priority for a while now. The greatest help now would be with my still unresolved problem of link creation, issue #76.

**Comment by TimVanMourik** [comment]
Closing this issue as it's all been implemented. I created a label 'code review' for future reference of implementational discussions.
