### ISSUE TITLE
A guide for contributing 

### ISSUE THREAD

**Issue by nemaniarjun** [TimVanMourik/GiraffeTools#87]
**Is your feature request related to a problem? Please describe.**
New comers should know how to start contributing to this repo.

**Describe the solution you'd like**
A clear and concise description of how to setup the dev env.

**Comment by TimVanMourik** [comment]
Yes, this is a very good point. I should have done this long ago, but I always struggle writing one-size-fits-all guidelines that are still useful. I just made a Slack channel for more easily discussing this.

**Comment by TimVanMourik** [comment]
Removing old issues. Although a new contributing guide is still kinda relevant.
