### ISSUE TITLE
Unable to remove a line on porcupine online version

### ISSUE THREAD

**Issue by Losses** [TimVanMourik/GiraffeTools#97]
**Describe the bug**
Remove a node won't remove it's line, and didn't find any way to remove a line...

**To Reproduce**
1. Add some node
2. Connect them
3. Delete one node

**Expected behavior**
Node removed,line removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1384036/48927428-c3e6d400-ef10-11e8-96a5-e9a18aae3d60.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Vivaldi
 - Version: 2.0.1309.29 (Stable channel) (32-bit)

**Comment by TimVanMourik** [comment]
Thanks for the issue, @Losses, I was just working on this today! Should be working soon. The plan is to make links clickable and deletable, and have links removed on cascade (also mentioned in #75). I'll keep you posted on the progress.

**Comment by TimVanMourik** [comment]
UPDATE: Link deletes on cascade after commit e99a5df0c997bf79fd22ca19548c8953860f7d79.

Clicking and deleting is still WIP.

**Comment by Losses** [comment]
Great!

**Comment by TimVanMourik** [comment]
UPDATE: Clicking and deleting has now been implemented as well, see commit d5921b4d92d0164c8f8397f26f3d8382ca3c4b19. Let me know if you can find bugs in the implementation. And feel free to make more issues with bug reports or feature requests. For me it gives a good indication of what parts I need to work on first :)

**Comment by TimVanMourik** [comment]
Yes, there is! But the links and sign-up method still needs to be implemented in the updated website design. I made an issue for this in #99 to do this. I'll see if I can complete it by tomorrow.
